version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: drug-discovery-assistant:latest
    working_dir: /app
    environment:
      GRADIO_SERVER_NAME: "0.0.0.0"
      GRADIO_SERVER_PORT: "7862"
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    ports:
      - "7862:7862"
    volumes:
      - ./:/app

