name: drug_discovery
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - rdkit
  - pytorch
  - cpuonly
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - pip
  - pip:
      - requests
      - fair-esm
      - gradio
      - optuna
      - tqdm
      - biopython
